# Generated by Django 2.2.3 on 2019-08-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_published',
        ),
    ]
